[colors.bright]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xdcdfe4"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 0

[shell]
program = "/home/fernandofh/.config/alacritty/init_tmux.sh"

[window.padding]
x = 8
y = 8
